services:
  namenode:
    image: bde2020/hadoop-base:2.0.0-hadoop3.2.1-java8
    container_name: hadoop-namenode
    hostname: namenode
    env_file:
      - ./hadoop.env
    ports:
      - "9870:9870"
      - "8088:8088"
      - "19888:19888"
    environment:
      CORE_CONF_fs_defaultFS: hdfs://namenode:8020
      START_LOCAL_DATANODE: "false"
    volumes:
      - ./shared:/shared
      - ./data/nn:/tmp/hadoop-root
      - ./history/.bash_history:/root/.bash_history
    command:
      - bash
      - /shared/compose-namenode.sh

  datanode:
    image: bde2020/hadoop-base:2.0.0-hadoop3.2.1-java8
    depends_on:
      - namenode
    env_file:
      - ./hadoop.env
    environment:
      CORE_CONF_fs_defaultFS: hdfs://namenode:8020
    volumes:
      - ./shared:/shared
      - /tmp/hadoop-root
    command:
      - bash
      - /shared/compose-datanode.sh

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    container_name: hive-metastore-postgresql
    hostname: hive-metastore-postgresql
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
    volumes:
      - ./data/hive/postgresql:/var/lib/postgresql/data

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    hostname: hive-metastore
    depends_on:
      - namenode
      - hive-metastore-postgresql
    env_file:
      - ./hadoop.env
    environment:
      CORE_CONF_fs_defaultFS: hdfs://namenode:8020
      HIVE_SITE_CONF_hive_metastore_uris: thrift://hive-metastore:9083
      HIVE_SITE_CONF_javax_jdo_option_ConnectionURL: jdbc:postgresql://hive-metastore-postgresql:5432/metastore
      HIVE_SITE_CONF_javax_jdo_option_ConnectionDriverName: org.postgresql.Driver
      HIVE_SITE_CONF_javax_jdo_option_ConnectionUserName: hive
      HIVE_SITE_CONF_javax_jdo_option_ConnectionPassword: hive
      SERVICE_PRECONDITION: namenode:9870 hive-metastore-postgresql:5432
    volumes:
      - ./shared:/shared
    command:
      - bash
      - /shared/start-hive-metastore.sh
    ports:
      - "9083:9083"

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    hostname: hive-server
    depends_on:
      - namenode
      - datanode
      - hive-metastore
    env_file:
      - ./hadoop.env
    environment:
      CORE_CONF_fs_defaultFS: hdfs://namenode:8020
      HIVE_SITE_CONF_hive_metastore_uris: thrift://hive-metastore:9083
      HIVE_SITE_CONF_javax_jdo_option_ConnectionURL: jdbc:postgresql://hive-metastore-postgresql:5432/metastore
      HIVE_SITE_CONF_javax_jdo_option_ConnectionDriverName: org.postgresql.Driver
      HIVE_SITE_CONF_javax_jdo_option_ConnectionUserName: hive
      HIVE_SITE_CONF_javax_jdo_option_ConnectionPassword: hive
      SERVICE_PRECONDITION: namenode:9870 hive-metastore:9083
    ports:
      - "10000:10000"
      - "10002:10002"
